#!/usr/bin/env bash
# This script displays a list of all currently running processes
# Shows all processes for all users, including those without a TTY
# Displays in a user-oriented format with process hierarchy

ps -e --forest -f
