#!/usr/bin/env bash
# 101-manage_my_process: Init script to manage the manage_my_process daemon
# Usage: 101-manage_my_process {start|stop|restart}

PROCESS_SCRIPT="./manage_my_process"  # Full path if required
PID_FILE="/var/run/my_process.pid"

case "$1" in
    start)
        if [ -f "$PID_FILE" ]
        then
            echo "manage_my_process is already running"
        else
            nohup "$PROCESS_SCRIPT" &>/dev/null &
            echo $! > "$PID_FILE"
            echo "manage_my_process started"
        fi
        ;;
    
    stop)
        if [ -f "$PID_FILE" ]
        then
            kill "$(cat "$PID_FILE")" && rm -f "$PID_FILE"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    
    restart)
        if [ -f "$PID_FILE" ]
        then
            kill "$(cat "$PID_FILE")" && rm -f "$PID_FILE"
        fi
        nohup "$PROCESS_SCRIPT" &>/dev/null &
        echo $! > "$PID_FILE"
        echo "manage_my_process restarted"
        ;;
    
    *)
        echo "Usage: 101-manage_my_process {start|stop|restart}"
        ;;
esac
