#!/usr/bin/env bash
# displays information about the School file

# Check if the school file exists
if [ -e school ];
then
    echo "school file exists"
    
    # Check if the school file is empty
    if [ -s school ];
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if the school file is a regular file
    if [ -f school ];
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
